### ISSUE TITLE
Error with crypt() in PHP7

### ISSUE THREAD

**Issue by vasa-c** [axypro/htpasswd#4]
crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format.

**Comment by AlokInsan** [comment]
A PHP Error was encountered
Severity: 8192

Message: crypt(): Supplied salt is not valid for DES. Possible bug in provided salt format.

Filename: phpass-0.1/PasswordHash.php

Line Number: 255

Backtrace:

File: D:\xampp\htdocs\App\application\libraries\phpass-0.1\PasswordHash.php
Line: 255
Function: crypt

File: D:\xampp\htdocs\App\application\libraries\Tank_auth.php
Line: 65
Function: CheckPassword

File: D:\xampp\htdocs\App\application\modules\Auth\controllers\auth.php
Line: 71
Function: login

File: D:\xampp\htdocs\App\index.php
Line: 315
Function: require_once


Please help me any one Urgent.
